[build]
target = "x86_64-pc-windows-gnu"
target-dir = "C:/Users/dhruv/.cargo-target/NaviFS"

[env]
CC_x86_64_pc_windows_gnu = "C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/bin/gcc.exe"
LIBRARY_PATH = "C:/Users/dhruv/OneDrive/Scans/Desktop/NaviFS"
DLLTOOL = "C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/bin/dlltool.exe"
DLLTOOL_x86_64_pc_windows_gnu = "C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/bin/dlltool.exe"

[target.x86_64-pc-windows-gnu]
linker = "C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/bin/gcc.exe"
ar = "C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/bin/ar.exe"

